### ISSUE TITLE
agregar README.md

### ISSUE THREAD

**Issue by mnrios1997** [Eugemo/DesfileMascotasJava#3]
Correspondería crear un archivo README.md para saber como ejecutar correctamente el proyecto

**Comment by Eugemo** [comment]
tienes razon, estaba pensando que podia ser asi:
`
# Titulo del Proyecto

DesfileMascotasJava

## Descripcion

El proyecto es una aplicacion de escritorio para la inscripcion a un desfile de mascotas. 
Desarrollado en java como una de las actividades del curso de Desarrollo web FullStack con Java de Polotic Misiones

## Comenzando el proyecto

- Se realizo con java en netbeans 8.2 con las siguientes librerias
- JDK 1.8
- EclipseLink JPA 2.1
- Base de datos MySQL 5.0.2

## Autor 

Maria Eugenia Moreno
[meugenia.moreno@gmail.com]

## Versines

- 0.1
  - Initial Release


## Comentarios

proyecto sin terminar
`
que te parece? queres hacerlo? te asigno

**Comment by mnrios1997** [comment]
Perfecto, ya lo realizo
